name: Run Build River Script

on: [push]

jobs:
  execute-bash:
    runs-on: ubuntu-latest # x86_64 빌드 머신 구동

    container:
      image: debian:trixie-slim # 데비안 13(Trixie) 환경 로드

    steps:
      - name: 소스 코드 가져오기
        uses: actions/checkout@v4

      - name: 스크립트 실행 권한 부여
        run: chmod +x auto_debuild_river.sh
        
      - name: 스크립트 실행
        run: ./auto_debuild_river.sh

      - name: 생성된 deb 파일 업로드
        uses: actions/upload-artifact@v4
        with:
          name: debian13-river-package
          path: "**/*.deb" # .deb 파일이 생성된 정확한 경로 지정
